version: '1.0'

services:

  client:
    image: 'node-services/client'
    stdin_open: true
    ports:
      - "3000:80"
    networks:
      - app
    build:
      context: ./client
      dockerfile: ./client/Dockerfile

  posts:
    image: 'node-services/posts'
    networks:
      - app
    build:
      context: server/posts
      dockerfile: ./posts/Dockerfile
    ports:
      - "4000:80"
    restart: unless-stopped
    container_name: posts
    depends_on:
      - event-bus

  comments:
    image: 'node-services/comments'
    networks:
      - app
    build:
      context: server/comments
      dockerfile: ./comments/Dockerfile
    ports:
      - "4001:80"
    restart: unless-stopped
    container_name: comments
    depends_on:
      - event-bus

  query:
    image: 'node-services/query'
    networks:
      - app
    build:
      context: server/query
      dockerfile: ./query/Dockerfile
    ports:
      - "4002:80"
    restart: unless-stopped
    container_name: query
    depends_on:
      - event-bus

  moderation:
    image: 'node-services/moderation'
    networks:
      - app
    build:
      context: server/moderation
      dockerfile: ./moderation/Dockerfile
    ports:
      - "4002:80"
    restart: unless-stopped
    container_name: query
    depends_on:
      - event-bus

  event-bus:
    image: 'node-services/eventbus'
    networks:
      - app
    build:
      context: server/event-bus
      dockerfile: ./event-bus/Dockerfile
    ports:
      - "4005:80"
    restart: unless-stopped
    container_name: event-bus

networks:
  app:
    driver: bridge
